name: admin
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.2.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  fluent_ui: ^4.8.7
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  eva_icons_flutter: ^3.1.0
  
dev_dependencies:
  build_runner: ^2.4.10
  envied_generator: ^0.5.4+1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  intl: 0.19.0

flutter:
  uses-material-design: true
  assets:
    - assets/