name: admin
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.2.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  appwrite: ^12.0.4
  cupertino_icons: ^1.0.6
  data_table_2: ^2.5.15
  eva_icons_flutter: ^3.1.0
  fluent_ui: ^4.9.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  riverpod_annotation: ^2.3.5

dev_dependencies:
  build_runner: ^2.4.12
  custom_lint: ^0.6.6
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13

dependency_overrides:
  intl: 0.19.0

flutter:
  uses-material-design: true
  assets:
    - assets/